{% set version = "0.15.1" %}

package:
  name: configargparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/ConfigArgParse/ConfigArgParse-{{ version }}.tar.gz
  sha256: baaf0fd2c1c108d007f402dab5481ac5f12d77d034825bf5a27f8224757bd0ac

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - configargparse

about:
  home: https://github.com/zorro3/ConfigArgParse
  license: MIT
  summary: replacement for argparse allowing options to be set via config files and/or env vars
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/zorro3/ConfigArgParse
  doc_url: https://github.com/zorro3/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
