{% set version = "1.0" %}

package:
  name: configargparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/ConfigArgParse/ConfigArgParse-{{ version }}.tar.gz
  sha256: bf378245bc9cdc403a527e5b7406b991680c2a530e7e81af747880b54eb57133

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - configargparse

about:
  home: https://github.com/zorro3/ConfigArgParse
  license: MIT
  summary: replacement for argparse allowing options to be set via config files and/or env vars
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/zorro3/ConfigArgParse
  doc_url: https://github.com/zorro3/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
