{% set version = "1.4" %}

package:
  name: configargparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/ConfigArgParse/ConfigArgParse-{{ version }}.tar.gz
  sha256: abef9ff44fb0091f0e3bb2ee7e5b26a02b5b62d45408a5272a9bd461f5b59b4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  source_files:
    - tests
    - setup.py
  requires:
    - pyyaml
    - pip
  imports:
    - configargparse
  commands:
    - pip check
    - python setup.py test

about:
  home: https://github.com/bw2/ConfigArgParse
  license: MIT
  summary: A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables.
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/bw2/ConfigArgParse
  doc_url: https://github.com/bw2/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
    - bollwyvl
