{% set version = "0.14.0" %}

package:
  name: configargparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/ConfigArgParse/ConfigArgParse-{{ version }}.tar.gz
  sha256: 2e2efe2be3f90577aca9415e32cb629aa2ecd92078adbe27b53a03e53ff12e91

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - configargparse

about:
  home: https://github.com/zorro3/ConfigArgParse
  license: MIT
  summary: replacement for argparse allowing options to be set via config files and/or env vars
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/zorro3/ConfigArgParse
  doc_url: https://github.com/zorro3/ConfigArgParse

extra:
  recipe-maintainers:
    - msarahan
