travis:
  secure:
    BINSTAR_TOKEN: l6LBnr/TQQbnksJ+jtYIHia+KVK0A967GHFc4v7IyLEN5OVCye3KPrvAg2GTvcHketIj4Bjppkn4eiztsxFN+WxVV2/rkDx2IHf/HLG/r0sDArpM6LckGlPg+KzJDyB35XcSFuqFRCcfHvUEJuK0cA18iO1oH13Pn3t3OtMjebs9QuLbBouAn8cljMbPxa64T2riWXfiJrheVya1b+eE4IG8SmSQiTRnp8TvjuPtXcrnsnNiZaPr/yVS4ll24lvM4nXKfAoAH3SscIy5bMGyLfptpLqDN8bULYaAuz9tPaZWD3xa7sznD3kkl4p+DTid6nqHZpX79/DphXjTtZcMJlJtEKir62KIQyOG66yJzHPHuu2Ll6S1ppSPxJPx6ZDiEcMCjyO4r/u7Qew5shdgcNwlfi76FJOcZyNW362QWoUY4gyo23hYJbxZyMqf41jdJ33kusjX9WWlsezhnAIAd6WzMNtfiiW5kdZb3k77jRECFQYRAucxP2FFgukQpnoYKmfiqKe5c6WrZ89jPmAcrL8nDlsOQFnk3hmWl3CxiRiCasbp9F+mI9PKDXngay1wHNKKa2+hYwACYo0GN7lsQPXGTEc78kYCUTqA68CWsdXYA3vgmahovz+1BAsBqLrDLGJfpIFyE7UIclK9z0lcdz2xAnPgujVDi3C9DSE9ybI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
